### ISSUE TITLE
Command "ConvertIDN" overwrites (at least) "TransferDomain"

### ISSUE THREAD

**Issue by tillwestpfahl** [centralnicgroup-opensource/rtldev-middleware-go-sdk#107]
When sending:
```
COMMAND = TransferDomain
DOMAIN = dömain.com
AUTH = myauth?code
```
the SDK does a `ConvertIDN` command, returns with code 200, but never actually sends the `TransferDomain` command.

**Comment by KaiSchwarz-cnic** [comment]
Thanks @tillwestpfahl for reporting. Task assigned. We'll keep you in the loop.

**Comment by Hermsi1337** [comment]
The cause for this issue is located here: https://github.com/centralnicgroup-opensource/rtldev-middleware-go-sdk/blob/master/apiclient/apiclient.go#L524

`newcmd` is initialized with `COMMAND=ConvertIDN`. But the `COMMAND`-key of `newcmd` is never overwritten with the initial `COMMAND`-value from the input-`cmd`.  
Also, the initial values of my `cmd` are lost, which results in even more strange behavior instead of just swallowing the initial `COMMAND`-value.

Initial `cmd`:

```
cmd = {map[string]interface{}} 
 0 = TECHCONTACT0 -> XX-XXXX-6
 1 = BILLINGCONTACT0 -> XX-XXXX-6
 2 = NAMESERVER0 -> ns01.XXXX.dev
 3 = NAMESERVER1 -> ns02.XXXX.dev
 4 = COMMAND -> AddDomain
 5 = DOMAIN -> döner.com
 6 = OWNERCONTACT0 -> XX-XXXX-11
 7 = ADMINCONTACT0 -> XX-XXXX-11
 ```

`cmd` after `autoIdnConvert`-foo:

```
newcmd = {map[string]string} 
 0 = COMMAND -> ConvertIDN
 1 = NAMESERVER0 -> ns01.XXXX.dev
 2 = NAMESERVER1 -> ns02.XXXX.dev
 3 = DOMAIN -> xn--dner-5qa.com
```

Without deep business-magic-knowledge it may be sufficient to assign the values to `cmd` instead of `newcmd` here: https://github.com/centralnicgroup-opensource/rtldev-middleware-go-sdk/blob/master/apiclient/apiclient.go#L573

And to return `cmd` at the end of the function instead of `newcmd`: https://github.com/centralnicgroup-opensource/rtldev-middleware-go-sdk/blob/master/apiclient/apiclient.go#L576
